version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
